/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 408ceb7a3328e872a9bab0f4dde99c0e)
interface __BaseEnv_Env {
  VITE_CLERK_SIGN_IN_URL: string;
  VITE_CLERK_SIGN_UP_URL: string;
  VITE_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: string;
  VITE_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL: string;
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: string;
  CLERK_SECRET_KEY: string;
  VITE_CLERK_PUBLISHABLE_KEY: string;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "VITE_CLERK_SIGN_IN_URL"
      | "VITE_CLERK_SIGN_UP_URL"
      | "VITE_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL"
      | "VITE_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL"
      | "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
      | "CLERK_SECRET_KEY"
      | "VITE_CLERK_PUBLISHABLE_KEY"
    >
  > {}
}
