/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: db448928878db7842b50df0c111f216f)
interface __BaseEnv_Env {
  VITE_CLERK_PUBLISHABLE_KEY: string;
  CLERK_SECRET_KEY: string;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "VITE_CLERK_PUBLISHABLE_KEY" | "CLERK_SECRET_KEY">
  > {}
}
